---
- name: Include checks/asserts
  ansible.builtin.include_tasks:
    file: asserts.yml

- name: Create cache directory
  local_action:
    module: ansible.builtin.file
    path: "{{ inventory_dir }}/.cache"
    state: directory
    mode: 0755
  run_once: True

- name: Initialize distribution-specific variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution | lower }}_{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution | lower }}.yml"
    - "{{ ansible_os_family | lower }}.yml"
  tags:
    - always

- name: Debug some shit
  ansible.builtin.debug:
    var: ansible_facts

- name: Include distribution specific tasks
  ansible.builtin.include_tasks: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution | lower }}.yml"
    - "{{ ansible_os_family | lower }}.yml"
    - unknown.yml

- name: Create directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - /etc/iocaine/config.d
    - /usr/share/data
    - /var/lib/iocaine

- name: Configure iocaine
  ansible.builtin.template:
    src: config.kdl.j2
    dest: /etc/iocaine/config.kdl
    mode: 0644
  tags:
    - always
    - conf
  notify: Restart iocaine service

- name: Download robots.json to localhost
  local_action:
    module: ansible.builtin.get_url
    url:
      https://github.com/ai-robots-txt/ai.robots.txt/raw/refs/heads/main/robots.json
    dest: "{{ inventory_dir }}/.cache/robots.json"
    mode: 0644
  run_once: True
  tags:
    - conf

- name: "Copy robots.json"
  copy:
    src: "{{ inventory_dir }}/.cache/robots.json"
    dest: "/usr/share/data/ai.robots.txt-robots.json"
    owner: root
    mode: 0644

- name: Create 00-ai.robots.txt.kdl
  ansible.builtin.copy:
    content: >
      declare-handler default {
        ai-robots-txt-path "/usr/share/data/ai.robots.txt-robots.json"
      }
    dest: /etc/iocaine/config.d/00-ai.robots.txt.kdl
  tags:
    - conf
  notify: Restart iocaine service

- name: Download shit
  ansible.builtin.get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
    mode: 0644
  tags:
    - conf
  with_items:
    - url: "https://archive.org/download/GeorgeOrwells1984/1984_djvu.txt"
      dest: /usr/share/data/1984.txt
    - url: "https://archive.org/download/ost-english-brave_new_world_aldous_huxley/Brave_New_World_Aldous_Huxley_djvu.txt"
      dest: /usr/share/data/brave-new-world.txt

- name: Create 01-sources.kdl
  ansible.builtin.copy:
    content: >
      declare-handler default {
        sources {
          training-corpus "/opt/iocaine/share/data/1984.txt" \
                          "/opt/iocaine/share/data/brave-new-world.txt"
          wordlists "/opt/iocaine/share/data/words.txt"
        }
      }
    dest: /etc/iocaine/config.d/01-sources.kdl
  tags:
    - conf
  notify: Restart iocaine service

- name: Create 02-metrics.kdl
  ansible.builtin.copy:
    content: >
      prometheus-server metrics {
        bind "127.0.0.1:42042"
        persist-path "/var/lib/iocaine/qmk-metrics.json"
        persist-interval "1h"
      }

      http-server default {
        use metrics=metrics
      }
    dest: /etc/iocaine/config.d/02-metrics.kdl
  tags:
    - conf
  notify: Restart iocaine service
